isudo: false
language: ruby
rvm:
- 2.2
branches:
  only:
  - jekyll
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --disable-external
after_success:
- git clone https://$GH_REF
- cd $(basename ${GH_REF%.git})
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- cp -R ../_site/* .
- git add -A .
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push -f "https://${DEPLOY_KEY}@${GH_REF}" ${TARGET_BRANCH} > /dev/null 2>&1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/mildronize/mildronize.github.io.git
  - TARGET_BRANCH: master
  - secure: BN2Rjs1aWXWfojiKg59Pm8ga1aTu8B5TfiNsZwBS9IcrPztlKG9hrEANQJdWydxoIoQAJBmoLiKoOS9SV8oP4RUmuNMybznpa9h1yWK45taADNi+iLlyASqW5/JW4xJauFm+kG0e3OB+ycTJSMCLYC5bscavRVZg9PbeKhQQt9mP49tlGU85Q94Un2+WlYLw387eR/XQQCIdOzy8DL0QS9xQ85GsTmmdXQlFDFEKBVFJgfZNlDqH5BjGTKSU24q6IfRq+lwtSbKnOmn31wfQ0ycWfiuaj4Qpybh33FF3cLym8HE8UJeHdPusyx2dphFRooSKh6a7VMNnCToQ05ueXJMY5MoDRVyf7WrkfU77NMYPG6MMVbh5vHZRqlfcRYuvJtbLWM3IWu+vOwzSsdGfRTfzqC+w3X6hq/cr6fcbWm+O2JgrA2GUGt2tjD0InqUCN4xljvIcrxTEG6Zh8PMIfQTCpxZaXWG2a2XvgUz0D0PZ1jhou0BluFUY0TBSteIedCukmc3VPgv4ByMzjMFz0tqlYmufJZ+o2V3nJlEahTAFIvnerLAKo3/DXir2tAMsxtgU8C8HMa1ZZXmO0pwLCZya+U2Nsxm8DZOtz7NTAta/d/emq+ufs4xmYDkZCzFr734y0nP5nPaZtIygmTjf+dmLNhgk/G5FDUuYWvRqlHI=
  - secure: uDANnL9RMA3RloULwLe/PzEWcP5aHOZ+pYqij2WT57ey74t8aET5w96j5SONTte+ip+ijbSasNLYzunZ7Z5MNRhDsb+EANq3M8Rmvaoh8FJcMkOSQpgH02tSiywrTM+wK4Qe4ac1gVnkYDhCXLAMDtFUpbp1fVMB6fl+qzZbvtRJMC1vZ89FwzkbasZttJCamKL8+nq7LWyotTDp/WTecSIhjEnyeKCCRwMzc+LC3EVn2ByqVs6eOyCCD0eByA0tFE0dU6cirN8Cbcrovq0LzotOZgJlGMOs2Kg9dgKoREPUAlO9e1hguBrdVCMdrofYU9iJ8Hqq24dTFB+Xc7ZeDM1gBCIiNmCg25xjj7zrnNl93bI8eOCmPtPv3ehbaq7S+4spIQhG7jHyPMzzZPEP2YtLNN6rWCBZxD2p+5N6uG2D/hjOzGMgXgt3W30m+836kPX9P9r8Oc29CYX5o9552aQpwpyvAF0kRBqsf+V50uTn4H/T6RxGkiuzqVOAlPokD1Uuf3OrM3/tmXXoXU02NzYmDQivbBH74VVKJzbew464AAfOjlGcyxDb2Lu4ZR3WJ+HoPr1tUEEz/6tUcU40fz3p2ZF8YrBCAHi0myI3NRqPpag9WB9WktTY1cAP4hYzUTWg/6htuigO7aMbZGWK2X9cbsibBX78m+U08e7TbGc=
