sudo: false
language: ruby
rvm:
- 2.2
branches:
  only:
  - jekyll
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --disable-external

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: jekyll
  target_branch: master