isudo: false
language: ruby
rvm:
- 2.2
branches:
  only:
  - jekyll
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --disable-external
after_success:
- git clone https://$GH_REF
- cd $(basename ${GH_REF%.git})
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- cp -R ../_site/* .
- git add -A .
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push -f "https://${DEPLOY_KEY}@${GH_REF}" ${TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/mildronize/mildronize.github.io.git
  - TARGET_BRANCH: master
  - secure: ipN3Daip3DPR/oMeMUiMBMKwOl/7jDI6F8cHblm/D5dn/D042rS6x8c/sE0aLeiJrnkv7UDMejBGjQKc8A4YHVvJHpt/77ZFz1zDGkji3z/OzerQCJHYWpuTUu8xnFo8YmAE7UqSihA9L20/eyDxe0/DBPBbvn240G5aguENzqDpydPV6A6L2OUD+0V9krCH/ud+JevU1APOfHxHwmkdG6jYQURoZSzxEwVBkoP94XeyPZ9UubpJx8svRk4I9EmlNOu3ihOjimfVlJl1NUAdeJah3x8Wcn5EZgt1P00n3PcPYSumaQfqmi+mO/2QrYh7+R+Rk8yVBjLcQqTXqf1nxiVz0VXbTNUdFZNW4QqqI4878DojWkPa6cirXkPhs06KJucR5S9VCP8Zwsyh4widHMBnNm7Egu4AlP7xAS2K+UvzQxqeGGYirn3jrLTLIdcqHiUtK2D3zDYa4L9kmtwUF/U9wj87311x5W6JeG5s4RME2Nq+Uity8mcWVDfMCSMd0A+ZvUiLpcx9tExYdH9WneBOYy3xXDzAOWMfdor0jEztV4f9Xn+UezwwRsMrH1JvWTv2IZgWTpEv+AW3GShrXxUUE4GSIqoG0xzB+03EckyiWb2jSCH61VgGwSIA9MM0YZZJ5Uhkzq5/DSOrthtWj99kd0h5jp5QI2HgEcH/GgU=
  - secure: SVV7RjXjzl7u5D4IrFYfI7rtdgfulDcnw6cdpmAq/nMcgbwV5lnlXW7/SGyvKkeb42N2LR2v2gB23WL5x7CKBbOzT1S9HDqwjFQ9sy12KlAdbLPhkTADUlbsYAxfp5yntVVqL9ruzfpyfPDVq67KNVzlzdEA3Efb+R3gUFYmg5TdvJcDo9x2BmRrdVjAxVObjttprvfTGkw4YFuhSSFt/OblWzFt8olPTeRATCKcF7S6vjFMnx79J+wB/9lv0ZcvIHQj625lDYiSAqNP1haJu7av8DD2lvg47ZmyTAjIOn6ecTbjr3jzab+TXmzZ6M5lMBuFuqUNBYi5SQecPVK47YI0rEOT0+NwqfcrvHMzPoxOGKPJCVuiQD0O6gc4Dvt4I478zMzF5ca/L5JIxfS+y565bd2SP8SNUFN7QXX+I398wbZEW4rNETv9rC6/qdPWmSNDEULTrRaKtyC4xG3YonEJ3pe0Xrw9Ptyl1PNqAhduQekP0G6OXVqgomS2QCUBq/V7/5asJ96blj95Vic1BzMlIBaczBRhblbuxMtuJK3CCrtiyfQPkNuQ3uJVb0pbdTEUu3nLzb1cjnyFJC2LDH9IrwYKZIg3fcBEvbU/s/+mp05ajWypDgpBXIplc1Gxc+LkTzW0yIsZg0M3iI4ljmXk/PbER8a0L9dZgfctS3w=
