version: '2'
services:
  live-server:
    image: mildronize/live-server-docker
    ports:
      - "8080:8080"
    depends_on:
      - jekyll-build
    volumes:
      - ./_site:/www
    container_name: jekyll-server

  jekyll-build:
    image: mildronize/mildronize.github.io
    volumes:
      - .:/src
    command: jekyll build --watch --incremental
    container_name: jekyll-builder
    environment:
        TIMEZONE: Asia/Bangkok
